apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-cluster
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 500M
    limits:
      cpu: 800m
      memory: 1Gi
